### ISSUE TITLE
One final overall comment

### ISSUE THREAD

**Issue by rajesh06** [pford221/mcmc_algorithms#6]
This is a very useful note and the dedicated candidate that takes the time to implement the code will gain significant knowledge. 

They said, I would offer (just my opinion) that this this a big ask for the junior candidate. 
- They will need an intermediate level of knowledge about R just to read the code.  
- They will need an intermediate knowledge of MCMC to understand the terminology.
This is not to say that I think we shouldn't be making this "ask" - but rather that we need to recognize what the ask entails.

On the R code - this is probably a bit picky but the candidate will also need to appreciate your coding style. I think a bit more consistency with the use of named arguments would be helpful. (I personally **always** name.) For example, on page 4, you name all arguments in the `rnorm` call but none in the `dbeta` call.

My final overall comment is that you might want to consider the use of numbered headings / subheadings. 

The note might also benefit from **more** subheadings.  For example, adding a subheading on page 3 after the numbered list will allow the reader the appreciate the transition from theory to practice. I'd offer a similar comment on Page 6 (a subheading to follow Figure 2) - which would allow the reader to appreciate the transition from practice to theory.

I think this will help the reader better understand the organization of the Note. That said, I offer this in context of how I think and that may not be representative of our candidates.

Thanks for your efforts on this.

Raj

**Comment by pford221** [comment]
Hey Raj,

It is not a requirement that they understand the R code. We state in the syllabus that R code will not explicitly be tested on the exam. The purpose of the code is for the curious candidate or even the practitioner to better understand the basics of the algorithms.

Regarding coding style, I did intend to name all my arguments but it appears I didn't always achieve that goal. I will go back through and add arguments, thanks for pointing out. In general, I strove for consistency in coding style throughout the note so I hope the curious candidate and reader can follow without issue.

I have added numbers to the main headings based on your prior comment. I'll look at adding some more subheadings but this ends up being a trickier task than first meets the eye. That's because the subsequent plots and text in the note get misaligned and the next thing I know I have a page that's only a single plot which looks weird. 

Thanks for the review on this. Perhaps we'll meet in-person in Philadelphia.

Best,
Patrick
